export const version = "0002_full_repository"

export const statements = [
  `ALTER TABLE oc_session
    CHANGE generation owner_generation BIGINT UNSIGNED NOT NULL,
    ADD COLUMN workspace_id VARCHAR(64) NULL AFTER project_id,
    ADD COLUMN parent_id VARCHAR(64) NULL AFTER workspace_id,
    ADD COLUMN slug VARCHAR(255) NOT NULL DEFAULT '' AFTER parent_id,
    ADD COLUMN path VARCHAR(2048) NULL AFTER directory,
    ADD COLUMN version VARCHAR(64) NOT NULL DEFAULT '' AFTER title,
    ADD COLUMN share_url VARCHAR(2048) NULL AFTER version,
    ADD COLUMN summary_json JSON NULL AFTER share_url,
    ADD COLUMN metadata_json JSON NULL AFTER summary_json,
    ADD COLUMN cost DOUBLE NOT NULL DEFAULT 0 AFTER metadata_json,
    ADD COLUMN tokens_input BIGINT NOT NULL DEFAULT 0 AFTER cost,
    ADD COLUMN tokens_output BIGINT NOT NULL DEFAULT 0 AFTER tokens_input,
    ADD COLUMN tokens_reasoning BIGINT NOT NULL DEFAULT 0 AFTER tokens_output,
    ADD COLUMN tokens_cache_read BIGINT NOT NULL DEFAULT 0 AFTER tokens_reasoning,
    ADD COLUMN tokens_cache_write BIGINT NOT NULL DEFAULT 0 AFTER tokens_cache_read,
    ADD COLUMN revert_json JSON NULL AFTER tokens_cache_write,
    ADD COLUMN permission_json JSON NULL AFTER revert_json,
    ADD COLUMN agent VARCHAR(255) NULL AFTER permission_json,
    ADD COLUMN model_json JSON NULL AFTER agent,
    ADD COLUMN compacting_at BIGINT NULL AFTER model_json,
    ADD COLUMN archived_at BIGINT NULL AFTER compacting_at,
    ADD INDEX oc_session_parent_idx (user_id, parent_id)`,
  `ALTER TABLE oc_run
    CHANGE generation owner_generation BIGINT UNSIGNED NOT NULL,
    CHANGE created_at started_at BIGINT NOT NULL,
    ADD COLUMN owner_instance_id VARCHAR(128) NOT NULL DEFAULT '' AFTER owner_generation,
    ADD COLUMN trigger_request_id VARCHAR(64) NOT NULL DEFAULT '' AFTER owner_instance_id,
    ADD COLUMN error_code VARCHAR(128) NULL AFTER status,
    ADD COLUMN error_json JSON NULL AFTER error_code,
    ADD COLUMN heartbeat_at BIGINT NULL AFTER error_json,
    ADD COLUMN finished_at BIGINT NULL AFTER heartbeat_at`,
  `ALTER TABLE oc_event_sequence
    ADD COLUMN owner_generation BIGINT UNSIGNED NOT NULL DEFAULT 1 AFTER seq`,
  `ALTER TABLE oc_event
    ADD COLUMN owner_generation BIGINT UNSIGNED NOT NULL DEFAULT 1 AFTER data`,
  `ALTER TABLE oc_session_input
    ADD COLUMN owner_generation BIGINT UNSIGNED NOT NULL DEFAULT 1 AFTER user_id,
    ADD COLUMN payload_hash VARCHAR(64) NOT NULL DEFAULT '' AFTER prompt,
    ADD COLUMN promoted_seq INT UNSIGNED NULL AFTER admitted_seq`,
  `CREATE TABLE oc_message (
    id VARCHAR(64) PRIMARY KEY,
    session_id VARCHAR(64) NOT NULL,
    user_id VARCHAR(128) NOT NULL,
    seq BIGINT UNSIGNED NOT NULL,
    data_json JSON NOT NULL,
    created_at BIGINT NOT NULL,
    updated_at BIGINT NOT NULL,
    UNIQUE KEY oc_message_session_seq_idx (session_id, seq),
    INDEX oc_message_session_created_id_idx (user_id, session_id, created_at, id),
    CONSTRAINT oc_message_session_fk FOREIGN KEY (session_id) REFERENCES oc_session(id) ON DELETE CASCADE
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`,
  `CREATE TABLE oc_session_message (
    id VARCHAR(64) PRIMARY KEY,
    session_id VARCHAR(64) NOT NULL,
    user_id VARCHAR(128) NOT NULL,
    type VARCHAR(128) NOT NULL,
    seq BIGINT UNSIGNED NOT NULL,
    data_json JSON NOT NULL,
    created_at BIGINT NOT NULL,
    updated_at BIGINT NOT NULL,
    UNIQUE KEY oc_session_message_session_seq_idx (session_id, seq),
    INDEX oc_session_message_type_seq_idx (user_id, session_id, type, seq),
    INDEX oc_session_message_created_id_idx (user_id, session_id, created_at, id),
    CONSTRAINT oc_session_message_session_fk FOREIGN KEY (session_id) REFERENCES oc_session(id) ON DELETE CASCADE
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`,
  `CREATE TABLE oc_part (
    id VARCHAR(64) PRIMARY KEY,
    message_id VARCHAR(64) NOT NULL,
    session_id VARCHAR(64) NOT NULL,
    user_id VARCHAR(128) NOT NULL,
    position BIGINT UNSIGNED NOT NULL,
    data_json JSON NOT NULL,
    created_at BIGINT NOT NULL,
    updated_at BIGINT NOT NULL,
    UNIQUE KEY oc_part_message_position_idx (message_id, position),
    INDEX oc_part_session_id_idx (user_id, session_id, id),
    CONSTRAINT oc_part_message_fk FOREIGN KEY (message_id) REFERENCES oc_message(id) ON DELETE CASCADE,
    CONSTRAINT oc_part_session_fk FOREIGN KEY (session_id) REFERENCES oc_session(id) ON DELETE CASCADE
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`,
  `CREATE TABLE oc_todo (
    session_id VARCHAR(64) NOT NULL,
    user_id VARCHAR(128) NOT NULL,
    position INT UNSIGNED NOT NULL,
    content TEXT NOT NULL,
    status VARCHAR(32) NOT NULL,
    priority VARCHAR(32) NOT NULL,
    created_at BIGINT NOT NULL,
    updated_at BIGINT NOT NULL,
    PRIMARY KEY (session_id, position),
    INDEX oc_todo_user_session_idx (user_id, session_id),
    CONSTRAINT oc_todo_session_fk FOREIGN KEY (session_id) REFERENCES oc_session(id) ON DELETE CASCADE
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`,
  `CREATE TABLE oc_session_context_epoch (
    session_id VARCHAR(64) PRIMARY KEY,
    user_id VARCHAR(128) NOT NULL,
    baseline TEXT NOT NULL,
    baseline_seq BIGINT UNSIGNED NOT NULL,
    snapshot_json JSON NOT NULL,
    updated_at BIGINT NOT NULL,
    INDEX oc_context_epoch_user_idx (user_id, session_id),
    CONSTRAINT oc_context_epoch_session_fk FOREIGN KEY (session_id) REFERENCES oc_session(id) ON DELETE CASCADE
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`,
  `CREATE TABLE oc_permission_request (
    id VARCHAR(64) PRIMARY KEY,
    session_id VARCHAR(64) NOT NULL,
    user_id VARCHAR(128) NOT NULL,
    status VARCHAR(32) NOT NULL,
    payload_json JSON NOT NULL,
    response_json JSON NULL,
    owner_generation BIGINT UNSIGNED NOT NULL,
    created_at BIGINT NOT NULL,
    updated_at BIGINT NOT NULL,
    INDEX oc_permission_pending_idx (user_id, status, created_at),
    CONSTRAINT oc_permission_session_fk FOREIGN KEY (session_id) REFERENCES oc_session(id) ON DELETE CASCADE
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`,
  `CREATE TABLE oc_question_request (
    id VARCHAR(64) PRIMARY KEY,
    session_id VARCHAR(64) NOT NULL,
    user_id VARCHAR(128) NOT NULL,
    status VARCHAR(32) NOT NULL,
    payload_json JSON NOT NULL,
    response_json JSON NULL,
    owner_generation BIGINT UNSIGNED NOT NULL,
    created_at BIGINT NOT NULL,
    updated_at BIGINT NOT NULL,
    INDEX oc_question_pending_idx (user_id, status, created_at),
    CONSTRAINT oc_question_session_fk FOREIGN KEY (session_id) REFERENCES oc_session(id) ON DELETE CASCADE
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`,
] as const
